frontend:
  image: zhuangy28/frontend
  tag: 402387b
  autoscaling:
    averageUtilization: 90
backend:
  image: zhuangy28/backend
  tag: 402387b
  autoscaling:
    averageUtilization: 90
database:
  enabled: true
  uri: pg-service
  username: postgres
  password: postgres
  
